version: '3.7'

networks:
    default: 
        external:
            name: hub-network
            name: hub-db-network

services:
    coinbase-service-bus-queue-host:
        container_name: "coinbase_service_bus_queue_host"
        image: "rhe89/hub-coinbase-service-bus-queue-host:latest"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - SQL_DB_COINBASE=${SQL_DB_COINBASE}
            - SERVICE_BUS_QUEUE_SAS=${SERVICE_BUS_QUEUE_SAS}
            - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
            - DOMAIN=Coinbase
            - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network

    coinbase-scheduled-host:
        container_name: "coinbase_scheduled_host"
        image: "rhe89/hub-coinbase-scheduled-host:latest"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - SQL_DB_COINBASE=${SQL_DB_COINBASE}
            - SERVICE_BUS_QUEUE_SAS=${SERVICE_BUS_QUEUE_SAS}
            - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
            - DOMAIN=Coinbase
            - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network

    coinbase-api:
        container_name: "coinbase_api"
        image: "rhe89/hub-coinbase-api:latest"
        hostname: "coinbase-api"
        ports:
            - "${COINBASE_API_PORT}:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=;http://+
            - SQL_DB_COINBASE=${SQL_DB_COINBASE}
            - SERVICE_BUS_QUEUE_SAS=${SERVICE_BUS_QUEUE_SAS}
            - AI_CONNECTION_STRING=${AI_CONNECTION_STRING}
            - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
            - DOMAIN=Coinbase
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network