version: '3.7'

networks:
    default: 
        external:
            name: hub-network
            name: hub-db-network
        
services:
    banking-service-bus-queue-host:
        container_name: "banking_service_bus_queue_host"
        image: "rhe89/hub-banking-service-bus-queue-host:latest"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - APP_CONFIG_CONNECTION_STRING=${APP_CONFIG_CONNECTION_STRING}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            - DOMAIN=Banking
            - CLOUD_ROLE_NAME=banking-service-bus-queue-host
        restart: on-failure:5
        networks:
            - hub-network
            - hub-db-network

    banking-scheduled-host:
        container_name: "banking_scheduled_host"
        image: "rhe89/hub-banking-scheduled-host:latest"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - APP_CONFIG_CONNECTION_STRING=${APP_CONFIG_CONNECTION_STRING}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            - DOMAIN=Banking
            - CLOUD_ROLE_NAME=banking-scheduled-host
        restart: on-failure:5
        networks:
            - hub-network
            - hub-db-network

    banking-api:
        container_name: "banking_api"
        image: "rhe89/hub-banking-api:latest"
        hostname: "banking-api"
        ports:
            - "${BANKING_API_PORT}:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=;http://+
            - APP_CONFIG_CONNECTION_STRING=${APP_CONFIG_CONNECTION_STRING}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            - DOMAIN=Banking
            - CLOUD_ROLE_NAME=banking-api
        restart: on-failure:5
        networks:
            - hub-network
            - hub-db-network

    banking-app:
        container_name: "banking_app"
        image: "rhe89/hub-banking-app:latest"
        hostname: "banking-app"
        ports:
            - "${BANKING_APP_PORT}:443"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=https://+
            - ASPNETCORE_HTTPS_PORT=${BANKING_APP_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
            - APP_CONFIG_CONNECTION_STRING=${APP_CONFIG_CONNECTION_STRING}
            - AZURE_TENANT_ID=${AZURE_TENANT_ID}
            - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
            - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
            - DOMAIN=Banking
            - CLOUD_ROLE_NAME=banking-web
        restart: on-failure:5
        volumes: 
            - "${WEB_CERT_FOLDER}:/https/"
        networks:
            - hub-network
            - hub-db-network