version: '3.7'

networks:
    hub-db-network:
        name: hub-db-network
services:
    hub-db:
        container_name: "hub_db"
        hostname: "hub-db"
        image: mcr.microsoft.com/mssql/server
        restart: always
        volumes:
            - hub-db-volume:/var/opt/mssql
        ports: 
            - "1533:1433"
        environment:
            - "SA_PASSWORD=${SQL_DB_PASSWORD}"
            - "ACCEPT_EULA=Y"
        networks:
            - hub-db-network

volumes:
    hub-db-volume:
        name: hub-db-volume
    

