version: '3.7'

networks:
    default: 
        external:
            name: hub-network
            name: hub-db-network

services:
    spreadsheet-service-bus-queue-host:
        container_name: "spreadsheet_service_bus_queue_host"
        image: "rhe89/hub-spreadsheet-service-bus-queue-host:latest"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - SQL_DB_SPREADSHEET=${SQL_DB_SPREADSHEET}
            - COINBASE_API_HOST=${COINBASE_API_HOST}
            - COINBASE_PRO_API_HOST=${COINBASE_PRO_API_HOST}
            - SBANKEN_API_HOST=${SBANKEN_API_HOST}
            - SERVICE_BUS_QUEUE_SAS=${SERVICE_BUS_QUEUE_SAS}
            - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
            - DOMAIN=Spreadsheet
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network
            
    spreadsheet-api:
        container_name: "spreadsheet_api"
        image: "rhe89/hub-spreadsheet-api:latest"
        hostname: "spreadsheet-api"
        ports:
            - "${SPREADSHEET_API_PORT}:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=http://+
            - SQL_DB_SPREADSHEET=${SQL_DB_SPREADSHEET}
            - SERVICE_BUS_QUEUE_SAS=${SERVICE_BUS_QUEUE_SAS}
            - STORAGE_ACCOUNT=${STORAGE_ACCOUNT}
            - AI_CONNECTION_STRING=${AI_CONNECTION_STRING}
            - DOMAIN=Spreadsheet
        restart: on-failure
        networks:
            - hub-network
            - hub-db-network

    spreadsheet-webapp:
        container_name: "spreadsheet_webapp"
        image: "rhe89/hub-spreadsheet-webapp:latest"
        hostname: "spreadsheet-webapp"
        ports:
            - "${SPREADSHEET_WEBAPP_PORT}:443"
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=https://+
            - ASPNETCORE_HTTPS_PORT=${SPREADSHEET_WEBAPP_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
            - AI_CONNECTION_STRING=${AI_CONNECTION_STRING}
            - DOMAIN=Spreadsheet
            - COSMOS_DB_CONNECTION_STRING=${COSMOS_DB_CONNECTION_STRING}
            - COSMOS_DB_SPREADSHEET=${COSMOS_DB_SPREADSHEET}
        restart: on-failure
        volumes: 
            - "${WEB_CERT_FOLDER}:/https/"
        networks:
            - hub-network
            - hub-db-network